auth:
  greeting: "Hallo"
EPD:
  driver: "IT8951"
  vcom: -2.37
  rotate: "CCW"
  spi_hz: 20000000
gfx:
  font: "/home/primer/data/fonts/schuldruck.ttf"
  emoji: "/home/primer/data/fonts/noto_emoji.ttf"
  image_path: "/home/primer/data/imgs/"
student:
  default_login: "primer-X"
  max_trials: 2
  session_dir: "/home/primer/students/"
mikroserver_stt:
  inference_host: "" #lesen-mikroserver inference host
  train_host: "...:8080"   #deepspeech training host
  port: "8080"
mikroserver_auth:
  auth_host: "..."          #lesen-mikroserver auth host
  port: "8080"
hmpl:
  training_trigger: 4
audio:
  soundcard: "plughw:CARD=seeed2micvoicec,DEV=0"  #check output of ```aplay -L``` to find out what to put here
  channels: 1
  rate: 16000
  wav_store_dir: "/home/primer/data/wavs/"
  ogg_store_dir: "/home/primer/data/oggs/"
  external_store_url: "https://fibel.digital/audio/"
  #denoiser: "/home/fibel/adenoiser_demo" #denoiser can be any kind of command line tool with 2 (INPUT_WAV OUTPUT_WAV) cli parameters
button:
  gpio: 17
  sleep_interval: 0.05
auth:
  hi: 'Hallo'
  bye: 'Auf wiedersehen'
gesture:
  mappings:
    "D": "U"
    "U": "D"
    "R": "R"
    "L": "L"
    "F": "F"
    "B": "B"
    "C": "C"
    "A": "A"
  reaction_time: 0.25
  entry_time: 0.4
  quit_time: 0.5
  busno: 1
  caseflag: 1
lesson0: "/home/fibel/personal_Primer/lessons/de/Panchatantra/Buch 1/affe.json"
#lesson0: "/home/primer/lessons/palope.json"
default_language: "de"
